services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-network  
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://uulen:Erdemuulen@db:5432/matedb
      SHADOW_DATABASE_URL: postgresql://postgres:Erdemsaihan@localhost:5432/myshopshadowdb
      JWT_SECRET: 'random'

networks:
  my-network:
    driver: bridge
